spring.application.name=emailService

machine.host=127.0.0.1

server.port=8002
grpc.server.port=9002
grpc.client.local-grpc-server.address=static://localhost:9002
grpc.server.enabled=true
logging.level.net.devh.boot.grpc.server=TRACE
logging.level.net.devh.boot.grpc.client=TRACE
logging.level.io.grpc=TRACE
logging.level.net.devh=DEBUG

spring.datasource.url=jdbc:mysql://${machine.host}:3306/DB_EMAIL_SERVICE?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



spring.kafka.bootstrap-servers=${machine.host}:29092
# ========== PRODUCER ==========
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ========== CONSUMER ==========
spring.kafka.consumer.group-id=email-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.type.mapping=com.banking.userService.dto.OtpRegister:com.ebanking.emailService.dto.OtpRegister,com.ebanking.transactionService.entity.Transaction:com.ebanking.emailService.dto.Transaction

spring.kafka.consumer.properties.spring.json.trusted.packages=*


# email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=itchauduongphattien@gmail.com
spring.mail.password=ovbj rtnq ibmu noyc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

send.email.from=itchauduongphattien@gmail.com