apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: tien22012003/authservice:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000   
            - containerPort: 9000   
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: USER_SERVICE
              value: user-service
            - name: USER_SERVICE_PORT
              value: "9001"
            - name: TRANSACTION_SERVICE
              value: transaction-service
            - name: TRANSACTION_SERVICE_PORT
              value: "9003"
