apiVersion: v1
kind: Service
metadata:
  name: email-service
spec:
  selector:
    app: email-service
  type: NodePort
  ports:
    - name: http
      port: 8002        # port bên trong cluster
      targetPort: 8002     # port trong container
      nodePort: 30082      # port để truy cập từ bên ngoài (phải trong khoảng 30000–32767)
    - name: grpc
      port: 9002
      targetPort: 9002
      nodePort: 30092
