spring.application.name=authService
server.port=8000
grpc.server.port=9000
machine.host=127.0.0.1

# K?t n?i MySQL
spring.datasource.url=jdbc:mysql://${machine.host}:3306/DB_AUTH?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret.key=chauduongphattien2201gmailcomsupersecretchauduongphattien2201gmailcomsupersecretchauduongphattien2201gmailcomsupersecretchauduongphattien2201gmailcomsupersecretchauduongphattien2201gmailcomsupersecretchauduongphattien2201gmailcomsupersecret


# http url
fcm.service=http://${machine.host}:8004/
chat.service=http://${machine.host}:8007/
services.ekyc.url=http://${machine.host}:8008/
service.trans.url=http://${machine.host}:8003/

# File upload limits (for proxying to ekycService)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB