pipeline {
    agent any

    tools {
        jdk 'java17'        // Tên JDK đã cấu hình trong Jenkins (Global Tool Configuration)
        maven 'maven3'      // Tên Maven đã cấu hình trong Jenkins (Global Tool Configuration)
    }

    stages {
        stage('Checkout') {
            steps {
                // Lấy code từ Git repo
                git branch: 'develop', url: 'https://github.com/ChauTienPro10/EBANKING'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
                sh 'mvn package -DskipTests'
            }
            post {
                success {
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }
    }

    post {
        success {
            echo 'Build & Test completed successfully!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
