spring.application.name=chatbotService
server.port=8007

machine.host=localhost

spring.datasource.url=jdbc:mysql://34.124.233.161:3306/DB_CHATBOT?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.ai.google.gemini.api-key=AIzaSyCGdygpsxKqCK_y5wZv5kTF8DSrpo_RlMY
gemini.api.key=AIzaSyCGdygpsxKqCK_y5wZv5kTF8DSrpo_RlMY

spring.ai.google.gemini.chat.options.model=gemini-2.5-flash
gemini.prompt=prompt


gemini.url=https://generativelanguage.googleapis.com/v1beta/models

