spring.application.name=chatbotService
server.port=8007

machine.host=localhost

spring.datasource.url=jdbc:mysql://${machine.host}:3306/DB_CHATBOT?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.ai.google.gemini.api-key=AIzaSyBnNM2AQB9xQ5BDBru7VJdtWyJxovfyZxo
gemini.api.key=AIzaSyBnNM2AQB9xQ5BDBru7VJdtWyJxovfyZxo

spring.ai.google.gemini.chat.options.model=gemini-2.5-flash
gemini.prompt=prompt


gemini.url=https://generativelanguage.googleapis.com/v1beta/models

