spring.application.name=chatbotService
server.port=8007

machine.host=127.0.0.1

spring.datasource.url=jdbc:mysql://${machine.host}:3306/DB_CHATBOT?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect



spring.ai.google.gemini.chat.options.model=gemini-2.5-flash
gemini.prompt=prompt

spring.ai.google.gemini.api-key=AIzaSyBM-Q-2xEs3JpWKs6d4xjcl14jpnHolcnY
gemini.api.key=AIzaSyBM-Q-2xEs3JpWKs6d4xjcl14jpnHolcnY

gemini.url=https://generativelanguage.googleapis.com/v1beta/models


# ===== List external DBs =====
external-dbs.names=DB_USER_SERVICE,DB_TRANSACTION_SERVICE,DB_FCM_SERVICE,DB_AUTH

# ===== USER SERVICE DB =====
external-dbs.DB_USER_SERVICE.url=jdbc:mysql://${machine.host}:3306/DB_USER_SERVICE
external-dbs.DB_USER_SERVICE.username=root
external-dbs.DB_USER_SERVICE.password=root@123
external-dbs.DB_USER_SERVICE.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== TRANSACTION SERVICE DB =====
external-dbs.DB_TRANSACTION_SERVICE.url=jdbc:mysql://${machine.host}:3306/DB_TRANSACTION_SERVICE
external-dbs.DB_TRANSACTION_SERVICE.username=root
external-dbs.DB_TRANSACTION_SERVICE.password=root@123
external-dbs.DB_TRANSACTION_SERVICE.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== FCM SERVICE DB =====
external-dbs.DB_FCM_SERVICE.url=jdbc:mysql://${machine.host}:3306/DB_FCM_SERVICE
external-dbs.DB_FCM_SERVICE.username=root
external-dbs.DB_FCM_SERVICE.password=root@123
external-dbs.DB_FCM_SERVICE.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== AUTH
external-dbs.DB_AUTH.url=jdbc:mysql://${machine.host}:3306/DB_AUTH
external-dbs.DB_AUTH.username=root
external-dbs.DB_AUTH.password=root@123
external-dbs.DB_AUTH.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== Safe default =====
external-dbs.hikari.maximum-pool-size=2
external-dbs.hikari.connection-timeout=3000