spring.application.name=AIService
server.port=8005
grpc.server.port=9005


spring.datasource.url=jdbc:mysql://34.124.233.161:3306/DB_AI_SERVICE?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true