export type RootStackParamList = {
    SignIn: undefined;
    SignUp: undefined;
    ForgotPassword: undefined;
    Home: undefined;
    Menu: undefined;
    AccountAndCard: undefined;
    Transfer: undefined;
    Withdraw: undefined;
    MobilePrepaid: undefined;
    PayBill: undefined;
    SaveOnline: undefined;
    CreditCard: undefined;
    TransactionReport: undefined;
    Beneficiary: undefined;
    Loan: undefined;
    Investments: undefined;
    Insurance: undefined;
    Profile: undefined;
    Settings: undefined;
    Support: undefined;
    Notifications: undefined;
    Search: undefined;
};
